robotiq_gripper_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController

    joints:
      - robotiq_85_left_knuckle_joint

    command_interfaces:
      - position
    state_interfaces:
      - position

    state_publish_rate: 25.0
    action_monitor_rate: 20.0

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.02

      robotiq_85_left_knuckle_joint:
        goal: 0.06
        trajectory: 0.1

    allow_partial_joints_goal: false
    interpolation_method: splines
